version: '3.8'

services:
  event-service:
    container_name: postgres-event
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: event
    volumes:
      - postgres-event:/data/postgres
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
  ticket-service:
    container_name: postgres-ticket
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: ticket
    volumes:
      - postgres-ticket:/data/postgres
volumes:
  postgres-event:
  mongo:
  postgres-ticket: