eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8801
          predicates:
            - Path=/api/v1/user/**
        - id: event-service
          uri: http://localhost:8802
          predicates:
            - Path=/api/v1/event/**



