spring:
  data:
    mongodb:
      uri: mongodb://mongouser:mongopassword@localhost:27017/userservice.user?authSource=admin
  application:
    name: user-service

server:
  port: 8801
  servlet:
    context-path: /api/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
