eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ticket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ticket-service
  cloud:
    openfeign:
      client:
        config:
          user:
            url: http://localhost:8080/api/v1/user
          event:
            url: http://localhost:8080/api/v1/event
server:
  port: 8803
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.web: debug

