eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ticket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ticket-service
server:
  port: 8803